// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZTP.EntityFramework;

#nullable disable

namespace ZTP.EntityFramework.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20220106154005_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ZTP.EntityFramework.Models.Level", b =>
                {
                    b.Property<int>("LvlNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LvlNumber"), 1L, 1);

                    b.Property<string>("LvlAssets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LvlEnemies")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LvlNumber");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("ZTP.EntityFramework.Models.ScoreBoard", b =>
                {
                    b.Property<int>("ScoreBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreBoardId"), 1L, 1);

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("ScoreBoardId");

                    b.HasIndex("LevelNumber");

                    b.ToTable("ScoreBoards");
                });

            modelBuilder.Entity("ZTP.EntityFramework.Models.ScoreBoard", b =>
                {
                    b.HasOne("ZTP.EntityFramework.Models.Level", "Level")
                        .WithMany("ScoreBoards")
                        .HasForeignKey("LevelNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("ZTP.EntityFramework.Models.Level", b =>
                {
                    b.Navigation("ScoreBoards");
                });
#pragma warning restore 612, 618
        }
    }
}
